In [201]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings 

warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

In [202]:
df_os = pd.read_csv('/Users/macintosh/Desktop/Dissertation/Smart-Inventory-Replenishment-System-for-E-Commerce/orders_and_shipments.csv')
df_inv = pd.read_csv('/Users/macintosh/Desktop/Dissertation/Smart-Inventory-Replenishment-System-for-E-Commerce/inventory.csv')

In [203]:
df_os.columns

Index(['Order ID ', ' Order Item ID ', ' Order YearMonth ', ' Order Year ',
       ' Order Month ', ' Order Day ', 'Order Time', 'Order Quantity',
       'Product Department', 'Product Category', 'Product Name',
       ' Customer ID ', 'Customer Market', 'Customer Region',
       'Customer Country', 'Warehouse Country', 'Shipment Year',
       'Shipment Month', 'Shipment Day', 'Shipment Mode',
       ' Shipment Days - Scheduled ', ' Gross Sales ', ' Discount % ',
       ' Profit '],
      dtype='object')

In [204]:
df_os.head(5)

,Order ID,Order Item ID,Order YearMonth,Order Year,Order Month,Order Day,Order Time,Order Quantity,Product Department,Product Category,Product Name,Customer ID,Customer Market,Customer Region,Customer Country,Warehouse Country,Shipment Year,Shipment Month,Shipment Day,Shipment Mode,Shipment Days - Scheduled,Gross Sales,Discount %,Profit
0,1,4381,202101,2021,1,1,2:48,1,Fan Shop,Water Sports,Pelican Sunstream 100 Kayak,7399,LATAM,Central America,Nicaragua,USA,2021,1,6,Same Day,3,200,0.09,100
1,2,29,202101,2021,1,1,3:30,1,Apparel,Cleats,Perfect Fitness Perfect Rip Deck,918,LATAM,South America,Brazil,Puerto Rico,2021,1,3,Standard Class,4,60,0.2,147
2,3,32,202101,2021,1,1,3:30,4,Footwear,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,918,LATAM,South America,Brazil,Puerto Rico,2021,1,3,Standard Class,4,400,0.06,245
3,4,33,202101,2021,1,1,3:30,5,Fan Shop,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,918,LATAM,South America,Brazil,Puerto Rico,2023,9,5,Standard Class,4,250,0.09,125
4,5,109801,202101,2021,1,1,4:12,5,Footwear,Electronics,Under Armour Women's Ignite Slide,6124,Europe,Eastern Europe,Belarus,USA,2021,1,5,Standard Class,4,160,0.15,75

In [205]:
df_os.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30871 entries, 0 to 30870
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Order ID                     30871 non-null  int64
 1    Order Item ID               30871 non-null  int64
 2    Order YearMonth             30871 non-null  int64
 3    Order Year                  30871 non-null  int64
 4    Order Month                 30871 non-null  int64
 5    Order Day                   30871 non-null  int64
 6   Order Time                   30871 non-null  object
 7   Order Quantity               30871 non-null  int64
 8   Product Department           30871 non-null  object
 9   Product Category             30871 non-null  object
 10  Product Name                 30871 non-null  object
 11   Customer ID                 30871 non-null  int64
 12  Customer Market              30871 non-null  object
 13  Customer Region              30871 non-null  object
 14  Customer Country             30871 non-null  object
 15  Warehouse Country            30871 non-null  object
 16  Shipment Year                30871 non-null  int64
 17  Shipment Month               30871 non-null  int64
 18  Shipment Day                 30871 non-null  int64
 19  Shipment Mode                30871 non-null  object
 20   Shipment Days - Scheduled   30871 non-null  int64
 21   Gross Sales                 30871 non-null  int64
 22   Discount %                  30871 non-null  object
 23   Profit                      30871 non-null  int64
dtypes: int64(14), object(10)
memory usage: 5.7+ MB

In [206]:
df_inv.head(10)

,Product Name,Year Month,Warehouse Inventory,Inventory Cost Per Unit
0,Perfect Fitness Perfect Rip Deck,202312,0,0.69517
1,Nike Men's Dri-FIT Victory Golf Polo,202312,2,1.29291
2,O'Brien Men's Neoprene Life Vest,202312,0,0.56531
3,Nike Men's Free 5.0+ Running Shoe,202312,1,1.26321
4,Under Armour Girls' Toddler Spine Surge Runni,202312,0,1.47648
5,Nike Men's CJ Elite 2 TD Football Cleat,202312,0,0.69591
6,Field & Stream Sportsman 16 Gun Fire Safe,202312,0,1.39148
7,Pelican Sunstream 100 Kayak,202312,0,0.20291
8,Diamondback Women's Serene Classic Comfort Bi,202312,0,1.54601
9,ENO Atlas Hammock Straps,202312,0,0.48119

In [207]:
# Strip column names of whitespaces
df_os.columns = df_os.columns.str.strip()
df_inv.columns = df_inv.columns.str.strip()

In [208]:
df_os.rename(columns={'Order YearMonth': 'Year Month'}, inplace=True)

In [209]:
# merge both files
merged_df = pd.merge(df_os, df_inv, on=['Product Name','Year Month'], how='left')

In [210]:
merged_df

,Order ID,Order Item ID,Year Month,Order Year,Order Month,Order Day,Order Time,Order Quantity,Product Department,Product Category,Product Name,Customer ID,Customer Market,Customer Region,Customer Country,Warehouse Country,Shipment Year,Shipment Month,Shipment Day,Shipment Mode,Shipment Days - Scheduled,Gross Sales,Discount %,Profit,Warehouse Inventory,Inventory Cost Per Unit
0,1,4381,202101,2021,1,1,2:48,1,Fan Shop,Water Sports,Pelican Sunstream 100 Kayak,7399,LATAM,Central America,Nicaragua,USA,2021,1,6,Same Day,3,200,0.09,100,132,2.03202
1,2,29,202101,2021,1,1,3:30,1,Apparel,Cleats,Perfect Fitness Perfect Rip Deck,918,LATAM,South America,Brazil,Puerto Rico,2021,1,3,Standard Class,4,60,0.2,147,254,0.49486
2,3,32,202101,2021,1,1,3:30,4,Footwear,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,918,LATAM,South America,Brazil,Puerto Rico,2021,1,3,Standard Class,4,400,0.06,245,18,2.25689
3,4,33,202101,2021,1,1,3:30,5,Fan Shop,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,918,LATAM,South America,Brazil,Puerto Rico,2023,9,5,Standard Class,4,250,0.09,125,442,2.34227
4,5,109801,202101,2021,1,1,4:12,5,Footwear,Electronics,Under Armour Women's Ignite Slide,6124,Europe,Eastern Europe,Belarus,USA,2021,1,5,Standard Class,4,160,0.15,75,18,2.23827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30866,30867,69831,202312,2023,12,31,3:53,1,Outdoors,Accessories,Team Golf Texas Longhorns Putter Grip,701,Pacific Asia,Eastern Asia,Japan,USA,2023,12,14,Second Class,2,25,0.04,58,2,2.24605
30867,30868,73992,202312,2023,12,31,4:56,1,Footwear,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,8837,Pacific Asia,Eastern Asia,South Korea,USA,2023,12,15,Second Class,2,100,0.25,245,1,1.26321
30868,30869,178348,202312,2023,12,31,7:03,1,Discs Shop,DVDs,DVDs,18586,Pacific Asia,Southeast Asia,Malaysia,Puerto Rico,2023,12,15,Second Class,2,164,0.09,79,64,2.03553
30869,30870,180390,202312,2023,12,31,13:21,1,Apparel,Women's Clothing,Summer dresses,20628,Pacific Asia,Southeast Asia,Philippines,USA,2023,12,29,Standard Class,4,216,0.2,99,13,1.36250
30870,30871,178391,202312,2023,12,31,22:06,1,Discs Shop,DVDs,DVDs,18629,Pacific Asia,Southeast Asia,Thailand,Puerto Rico,2023,12,15,Standard Class,4,164,0.01,79,64,2.03553

In [211]:
merged_df.isnull().sum()

Order ID                     0
Order Item ID                0
Year Month                   0
Order Year                   0
Order Month                  0
Order Day                    0
Order Time                   0
Order Quantity               0
Product Department           0
Product Category             0
Product Name                 0
Customer ID                  0
Customer Market              0
Customer Region              0
Customer Country             0
Warehouse Country            0
Shipment Year                0
Shipment Month               0
Shipment Day                 0
Shipment Mode                0
Shipment Days - Scheduled    0
Gross Sales                  0
Discount %                   0
Profit                       0
Warehouse Inventory          0
Inventory Cost Per Unit      0
dtype: int64

In [212]:
# Combine into a datetime string
merged_df['Order Date'] = pd.to_datetime(
    merged_df['Order Year'].astype(str) + '-' +
    merged_df['Order Month'].astype(str).str.zfill(2) + '-' +
    merged_df['Order Day'].astype(str).str.zfill(2)
)

merged_df['Shipment Date'] = pd.to_datetime(
    merged_df['Shipment Year'].astype(str) + '-' +
    merged_df['Shipment Month'].astype(str).str.zfill(2) + '-' +
    merged_df['Shipment Day'].astype(str).str.zfill(2) 
)

In [213]:
merged_df

,Order ID,Order Item ID,Year Month,Order Year,Order Month,Order Day,Order Time,Order Quantity,Product Department,Product Category,Product Name,Customer ID,Customer Market,Customer Region,Customer Country,Warehouse Country,Shipment Year,Shipment Month,Shipment Day,Shipment Mode,Shipment Days - Scheduled,Gross Sales,Discount %,Profit,Warehouse Inventory,Inventory Cost Per Unit,Order Date,Shipment Date
0,1,4381,202101,2021,1,1,2:48,1,Fan Shop,Water Sports,Pelican Sunstream 100 Kayak,7399,LATAM,Central America,Nicaragua,USA,2021,1,6,Same Day,3,200,0.09,100,132,2.03202,2021-01-01,2021-01-06
1,2,29,202101,2021,1,1,3:30,1,Apparel,Cleats,Perfect Fitness Perfect Rip Deck,918,LATAM,South America,Brazil,Puerto Rico,2021,1,3,Standard Class,4,60,0.2,147,254,0.49486,2021-01-01,2021-01-03
2,3,32,202101,2021,1,1,3:30,4,Footwear,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,918,LATAM,South America,Brazil,Puerto Rico,2021,1,3,Standard Class,4,400,0.06,245,18,2.25689,2021-01-01,2021-01-03
3,4,33,202101,2021,1,1,3:30,5,Fan Shop,Indoor/Outdoor Games,O'Brien Men's Neoprene Life Vest,918,LATAM,South America,Brazil,Puerto Rico,2023,9,5,Standard Class,4,250,0.09,125,442,2.34227,2021-01-01,2023-09-05
4,5,109801,202101,2021,1,1,4:12,5,Footwear,Electronics,Under Armour Women's Ignite Slide,6124,Europe,Eastern Europe,Belarus,USA,2021,1,5,Standard Class,4,160,0.15,75,18,2.23827,2021-01-01,2021-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30866,30867,69831,202312,2023,12,31,3:53,1,Outdoors,Accessories,Team Golf Texas Longhorns Putter Grip,701,Pacific Asia,Eastern Asia,Japan,USA,2023,12,14,Second Class,2,25,0.04,58,2,2.24605,2023-12-31,2023-12-14
30867,30868,73992,202312,2023,12,31,4:56,1,Footwear,Cardio Equipment,Nike Men's Free 5.0+ Running Shoe,8837,Pacific Asia,Eastern Asia,South Korea,USA,2023,12,15,Second Class,2,100,0.25,245,1,1.26321,2023-12-31,2023-12-15
30868,30869,178348,202312,2023,12,31,7:03,1,Discs Shop,DVDs,DVDs,18586,Pacific Asia,Southeast Asia,Malaysia,Puerto Rico,2023,12,15,Second Class,2,164,0.09,79,64,2.03553,2023-12-31,2023-12-15
30869,30870,180390,202312,2023,12,31,13:21,1,Apparel,Women's Clothing,Summer dresses,20628,Pacific Asia,Southeast Asia,Philippines,USA,2023,12,29,Standard Class,4,216,0.2,99,13,1.36250,2023-12-31,2023-12-29
30870,30871,178391,202312,2023,12,31,22:06,1,Discs Shop,DVDs,DVDs,18629,Pacific Asia,Southeast Asia,Thailand,Puerto Rico,2023,12,15,Standard Class,4,164,0.01,79,64,2.03553,2023-12-31,2023-12-15

In [214]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30871 entries, 0 to 30870
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Order ID                   30871 non-null  int64
 1   Order Item ID              30871 non-null  int64
 2   Year Month                 30871 non-null  int64
 3   Order Year                 30871 non-null  int64
 4   Order Month                30871 non-null  int64
 5   Order Day                  30871 non-null  int64
 6   Order Time                 30871 non-null  object
 7   Order Quantity             30871 non-null  int64
 8   Product Department         30871 non-null  object
 9   Product Category           30871 non-null  object
 10  Product Name               30871 non-null  object
 11  Customer ID                30871 non-null  int64
 12  Customer Market            30871 non-null  object
 13  Customer Region            30871 non-null  object
 14  Customer Country           30871 non-null  object
 15  Warehouse Country          30871 non-null  object
 16  Shipment Year              30871 non-null  int64
 17  Shipment Month             30871 non-null  int64
 18  Shipment Day               30871 non-null  int64
 19  Shipment Mode              30871 non-null  object
 20  Shipment Days - Scheduled  30871 non-null  int64
 21  Gross Sales                30871 non-null  int64
 22  Discount %                 30871 non-null  object
 23  Profit                     30871 non-null  int64
 24  Warehouse Inventory        30871 non-null  int64
 25  Inventory Cost Per Unit    30871 non-null  float64
 26  Order Date                 30871 non-null  datetime64[ns]
 27  Shipment Date              30871 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(15), object(10)
memory usage: 6.6+ MB

In [215]:
# Drop unnecessary columns
merged_df.drop(['Year Month', 'Order Day', 'Shipment Day', 'Order Year', 'Order Month', 'Shipment Year', 'Shipment Month', 'Order Time'], axis=1, inplace=True)

In [216]:
# Check for null values
merged_df.isnull().sum()

Order ID                     0
Order Item ID                0
Order Quantity               0
Product Department           0
Product Category             0
Product Name                 0
Customer ID                  0
Customer Market              0
Customer Region              0
Customer Country             0
Warehouse Country            0
Shipment Mode                0
Shipment Days - Scheduled    0
Gross Sales                  0
Discount %                   0
Profit                       0
Warehouse Inventory          0
Inventory Cost Per Unit      0
Order Date                   0
Shipment Date                0
dtype: int64

In [217]:
# Check for duplicates
merged_df.duplicated().any()

False

In [218]:
# save to csv 
merged_df.to_csv('merged.csv', index=False)